AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Jenkins Automation - Linux Demo (Ubuntu 22.04 LTS)
  Provisions a t3.medium EC2 instance, installs Jenkins via Track 2 (Pure Python),
  and configures Jenkins to listen natively on port 8000.
  Security group locked to deployer IP. SSH key consistent across re-deploys.

# ─── PARAMETERS ───────────────────────────────────────────────────────────────
Parameters:

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: perforce-jenkins-demo
    Description: EC2 Key Pair for SSH access

  DeployerIP:
    Type: String
    Description: Your public IP in CIDR notation. Restricts SSH and Jenkins access to this IP only. Pass at deploy time using --parameter-overrides DeployerIP="$(curl -s https://checkip.amazonaws.com).Trim()/32"

  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
    Description: EC2 instance type t3.medium recommended

  UbuntuAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
    Description: Latest Ubuntu 22.04 LTS AMI. Resolved automatically via SSM at deploy time

  ScriptURL:
    Type: String
    Default: https://raw.githubusercontent.com/zambrano-luis/jenkins-automation/main/track2-python/install_jenkins.py
    Description: Raw GitHub URL to the Python installer script

# ─── MAPPINGS ─────────────────────────────────────────────────────────────────
# No static AMI mappings needed. AMI resolved dynamically via SSM Parameter
# Store at deploy time, always returning the latest official Canonical Ubuntu
# 22.04 LTS image for the deployed region. This avoids stale AMI ID failures.

# ─── RESOURCES ────────────────────────────────────────────────────────────────
Resources:

  # ── Security Group ──────────────────────────────────────────────────────────
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: jenkins-demo-sg
      GroupDescription: Jenkins demo. SSH and port 8000 restricted to deployer IP
      SecurityGroupIngress:

        # SSH - locked to deployer IP only
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref DeployerIP
          Description: SSH access. Deployer IP only

        # Jenkins on port 8000 - locked to deployer IP only
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: !Ref DeployerIP
          Description: Jenkins UI. Deployer IP only

      Tags:
        - Key: Name
          Value: jenkins-demo-sg
        - Key: Project
          Value: jenkins-automation

  # ── EC2 Instance ─────────────────────────────────────────────────────────────
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      ImageId: !Ref UbuntuAMI
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup

      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log all output to CloudWatch-friendly location
          exec > >(tee /var/log/jenkins-install.log) 2>&1

          echo "==> Downloading Jenkins installer from GitHub..."
          curl -fsSL -o /tmp/install_jenkins.py ${ScriptURL}

          echo "==> Running Jenkins installer..."
          python3 /tmp/install_jenkins.py

          echo "==> Installation complete. Jenkins should be running on port 8000."

      Tags:
        - Key: Name
          Value: jenkins-demo-linux
        - Key: Project
          Value: jenkins-automation
        - Key: Track
          Value: Track2-Python

# ─── OUTPUTS ──────────────────────────────────────────────────────────────────
Outputs:

  InstanceID:
    Description: EC2 Instance ID
    Value: !Ref JenkinsInstance

  PublicIP:
    Description: Public IP address of the Jenkins instance
    Value: !GetAtt JenkinsInstance.PublicIp

  JenkinsURL:
    Description: Jenkins URL. Open this in your browser once provisioning completes
    Value: !Sub http://${JenkinsInstance.PublicIp}:8000

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub ssh -i perforce-jenkins-demo.pem ubuntu@${JenkinsInstance.PublicIp}

  InstallLog:
    Description: View installation log on the instance
    Value: sudo cat /var/log/jenkins-install.log
